## Results Summary

This notebook will focus on comparing the performance of models in 04_model_training.ipynb.

In [ ]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [17]:
# Load results
with open("../data/results/model_results.pkl", "rb") as f:
    results = pickle.load(f)

confusion_matrices = results["confusion_matrices"]
auc_scores = results["auc_scores"]
classification_reports = results["classification_reports"]

In [18]:
for model_name, confusion_matrix in confusion_matrices.items():
    print(f"Confusion Matrix for {model_name}:\n{confusion_matrix}")

Confusion Matrix for Decision Tree:
[[ 14   2  15]
 [  9 113  64]
 [  4   1   5]]
Confusion Matrix for Random Forest:
[[ 24   5   2]
 [ 12 155  19]
 [  3   4   3]]
Confusion Matrix for XGBoost:
[[ 21  10   0]
 [  9 177   0]
 [  3   7   0]]
Confusion Matrix for AdaBoost:
[[ 19   2  10]
 [  3 127  56]
 [  2   2   6]]
Confusion Matrix for Logistic Regression:
[[ 22   4   5]
 [  9 123  54]
 [  2   3   5]]
Confusion Matrix for k-Nearest Neighbors:
[[ 13  15   3]
 [  6 177   3]
 [  2   8   0]]
Confusion Matrix for Support Vector Machine:
[[ 12   6  13]
 [  2 163  21]
 [  2   5   3]]
Confusion Matrix for Neural Network:
[[ 22   4   5]
 [ 11 145  30]
 [  3   5   2]]


In [38]:
# Iterate through the models and combine the macro precision, recall, f1-score, and ROC AUC into a single DataFrame
results_comparison = {}

for model_name in classification_reports.keys():
    classification_report = classification_reports[model_name]
    auc_score = auc_scores[model_name]
    
    results_comparison[model_name] = {
        "Macro Precision" : classification_report["macro avg"]["precision"],
        "Macro Recall" : classification_report["macro avg"]["recall"],
        "Macro F1" : classification_report["macro avg"]["f1-score"],
        "ROC AUC" : auc_scores[model_name]
    }
    
results_comparison_df = pd.DataFrame.from_dict(results_comparison, orient="index")
results_comparison_df = results_comparison_df.round(4).sort_values("ROC AUC", ascending=False)

print(f"Model results comparison:\n{results_comparison_df}")

Model results comparison:
                        Macro Precision  Macro Recall  Macro F1  ROC AUC
AdaBoost                         0.6148        0.6319    0.5462   0.8182
Logistic Regression              0.5636        0.6237    0.5337   0.8170
Neural Network                   0.5356        0.5631    0.5316   0.8085
Random Forest                    0.5618        0.6358    0.5826   0.8040
Support Vector Machine           0.5893        0.5211    0.5146   0.7976
XGBoost                          0.5162        0.5430    0.5293   0.7961
Decision Tree                    0.5174        0.5197    0.4458   0.7596
k-Nearest Neighbors              0.5013        0.4570    0.4724   0.7459


In [48]:
# Iterate through the models and compare the ROC AUC scores
auc_comparison = {}

for model_name, auc_score in auc_scores.items():
    
    auc_comparison[model_name] = {
        "ROC AUC" : auc_score
    }
    
    auc_comparisonn_df = pd.DataFrame.from_dict(auc_comparison, orient="index")
    
auc_comparisonn_df = auc_comparisonn_df.round(4).sort_values("ROC AUC", ascending=False)

print(f"ROC AUC comparison:\n{auc_comparisonn_df}")

ROC AUC comparison:
                        ROC AUC
AdaBoost                 0.8182
Logistic Regression      0.8170
Neural Network           0.8085
Random Forest            0.8040
Support Vector Machine   0.7976
XGBoost                  0.7961
Decision Tree            0.7596
k-Nearest Neighbors      0.7459


In [42]:
# Iterate through the models and compare the recall scores of "Diabetes_yes"
yes_recall_comparison = {}

for model_name, classification_report in classification_reports.items():
    
    yes_recall_comparison[model_name] = {
        "Recall" : classification_report["Diabetes_yes"]["recall"]
    }
    
    yes_recall_comparison_df = pd.DataFrame.from_dict(yes_recall_comparison, orient="index")
    
yes_recall_comparison_df = yes_recall_comparison_df.round(4).sort_values("Recall", ascending=False)

print(f"[Diabetes_yes] Recall comparison:\n{yes_recall_comparison_df}")

[Diabetes_yes] Recall comparison:
                        Recall
Random Forest           0.7742
Logistic Regression     0.7097
Neural Network          0.7097
XGBoost                 0.6774
AdaBoost                0.6129
Decision Tree           0.4516
k-Nearest Neighbors     0.4194
Support Vector Machine  0.3871


In [43]:
# Iterate through the models and compare the precision scores of "Diabetes_no"
no_precision_comparison = {}

for model_name, classification_report in classification_reports.items():
    
    no_precision_comparison[model_name] = {
        "Precision" : classification_report["Diabetes_no"]["precision"]
    }
    
    no_precision_comparison_df = pd.DataFrame.from_dict(no_precision_comparison, orient="index")
    
no_precision_comparison_df = no_precision_comparison_df.round(4).sort_values("Precision", ascending=False)

print(f"[Diabetes_no] Precision comparison:\n{no_precision_comparison_df}")

[Diabetes_no] Precision comparison:
                        Precision
Decision Tree              0.9741
AdaBoost                   0.9695
Logistic Regression        0.9462
Random Forest              0.9451
Neural Network             0.9416
Support Vector Machine     0.9368
XGBoost                    0.9124
k-Nearest Neighbors        0.8850


In [44]:
# Iterate through the models and compare the recall scores of "Diabetes_borderline"
borderline_recall_comparison = {}

for model_name, classification_report in classification_reports.items():
    
    borderline_recall_comparison[model_name] = {
        "Recall" : classification_report["Diabetes_borderline"]["recall"]
    }
    
    borderline_recall_comparison_df = pd.DataFrame.from_dict(borderline_recall_comparison, orient="index")
    
borderline_recall_comparison_df = borderline_recall_comparison_df.round(4).sort_values("Recall", ascending=False)

print(f"[Diabetes_borderline] Recall comparison:\n{borderline_recall_comparison_df}")

[Diabetes_borderline] Recall comparison:
                        Recall
AdaBoost                   0.6
Decision Tree              0.5
Logistic Regression        0.5
Random Forest              0.3
Support Vector Machine     0.3
Neural Network             0.2
XGBoost                    0.0
k-Nearest Neighbors        0.0
